version: '3'

services: 
  app:
    build:
      context: ../
      dockerfile: ./docker/app.docker
    image: pydocker:app
    command: python pydocker/manage.py runserver 0.0.0.0:8000
    container_name: pydocker-app
    restart: on-failure
    volumes:
    - ..:/app
    ports:
    - "8002:8000"
